---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.29.0
      hooks:
          - id: yamllint
            args: [--format, parsable, -d, relaxed]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
